logging:
    level:
        com:
            example:
                chatbackend: DEBUG
        root: INFO
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
server:
    port: 8081
spring:
    application:
        name: backend
    kafka:
        bootstrap-servers: ${KAFKA_SERVERS:kafka1:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    websocket:
        path: /chat
